
spring:
  datasource:
    name: abeiyun
    url: jdbc:mysql://localhost:3306/abeiyun?characterEncoding=utf-8
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver





